### ISSUE TITLE
PID Controller

### ISSUE THREAD

**Issue by flodus** [rsciriano/ESPHome-OpenTherm#21]
Hello,
I've installed your esphome opentherm by commenting arduino version and replace ESP Async WebServer library, by `esphome/ESPAsyncWebServer-esphome @ 2.1.0`
I've got the diyless opentherm shield
and I've got this boiler `https://www.viessmann.fr/fr/chauffage-maison-individuelle/chaudiere-gaz/condensation/vitodens-100-w-vitodens-111-w.html` Vitodens 100 w
I looked a bit at the doc `https://esphome.io/components/climate/pid.html?highlight=climate`

and for the autotune of the PID, they explain `https://esphome.io/components/climate/pid.html?highlight=climate#autotuning`
that we must put the values

```
     control_parameters:
       kp: 0.0
       ki: 0.0
       kd: 0.0

```
and start the autotune
in your opentherm.yaml file there are already the values

```
     control_parameters:
       kp: 0.38197
       ki: 0.01012
       kd: 3.60387

```
should we redo the autotune for us or should we keep your conf ?

thank you in advance for your reply and thank you for your great work
