### ISSUE TITLE
Setting upper an lower limits in boiler

### ISSUE THREAD

**Issue by bigbrother72** [rsciriano/ESPHome-OpenTherm#29]
Hello

My boiler have limits 45-85C.  But i want to set in opentherm PID settings limits 50-75C for water in boiler.

How i can set upper and lower limits in opentherm temostat?

**Comment by rsciriano** [comment]
Hi @bigbrother72 ,

You can do it like this:

```yaml
climate:
  - platform: custom
    lambda: |-
      OpenthermComponent *openthermComp = (OpenthermComponent*) opentherm;
      return {
        openthermComp->hotWaterClimate, 
        openthermComp->heatingWaterClimate
      };
    climates:
      - id: hot_water
        name: "Hot water"
      - id: heating_water
        name: "Heating water"
        visual:
          min_temperature: 30 °C
          max_temperature: 85 °C        
```

The custom climates support the same configuration as [core climate](https://esphome.io/components/climate/index.html#config-climate)
