### ISSUE TITLE
Compile fails with: fatal error: esphome/components/text_sensor/text_sensor.h: No such file or directory

### ISSUE THREAD

**Issue by CuriousTimo** [rsciriano/ESPHome-OpenTherm#65]
I'm trying to compile with ESPHome on Home Assistant and get an error: Compile fails with: fatal error: esphome/components/text_sensor/text_sensor.h: No such file or directory

- ESPHome 2024.9.2
- Home Assistant 2024.10.1

```
substitutions:
  name: opentherm-gateway
  friendly_name: OpenTherm Gateway
  board: d1_mini

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

esp8266:
  board: ${board}

external_components:
  - source: github://gduteil/OpenThermGateway
    components: [ openthermgw ]

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_opentherm-gateway_key

ota:
  platform: esphome  
  password: !secret esphome_ota_password

safe_mode:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Opentherm Gateway Fallback"
    password: "mypasswordishidden"

captive_portal:

openthermgw:
  pin_thermostat_in: 2
  pin_thermostat_out: 4
  pin_boiler_in: 12
  pin_boiler_out: 13

  ch_enable: true
  dhw_enable: true
  cooling_enable: false
  otc_active: false
  ch2_active: false

one_wire:
  - platform: gpio
    pin: GPIO14

sensor:
  - platform: dallas_temp
    address: 0x3a46258f34640000
    name: "T°C OTGW"
```

[logs_opentherm-gateway_compile.txt](https://github.com/user-attachments/files/17421557/logs_opentherm-gateway_compile.txt)
